spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: 1234
        platform: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: validate